### ISSUE TITLE
Needs --version

### ISSUE THREAD

**Issue by tseemann** [dnbaker/bonsai#10]
```
% bonsai --version
bonsai 0.2
```

**Comment by dnbaker** [comment]
Would something like this be acceptable?

```
% ./bonsai --version
bonsai|v0.1-281-gf324
% ./bonsai -v
bonsai|v0.1-281-gf324
```

I'll be incrementing the minor version soon, but I wanted to ask RE: formatting.

**Comment by tseemann** [comment]
No it needs to be a space character.

Also, official releases shouldn't have git tags etc.
